import 'package:dart_json_annotations/dart_json_annotations.dart';

part 'api_testing.gen.dart';

/// Example: Generic union class with converter functions
/// 
/// For generic union classes, `fromJson` and `toJson` must accept converter functions
/// to handle the generic type parameter, similar to regular generic classes.
@Model(fromJson: true, toJson: true, equatable: true)
sealed class Result<T> {
  const Result._();
  
  // For generic union classes, fromJson must accept a converter function
  // The _$ResultFromJson helper will be generated by the code generator
  factory Result.fromJson(
    Map<String, dynamic> json,
    T Function(Object?) fromJsonT,
  ) => _$ResultFromJson(json, fromJsonT);
  
  // toJson should also accept a converter function
  // The _$ResultToJson helper will be generated by the code generator
  Map<String, dynamic> toJson(T Function(T) toJsonT) => $ResultJson(this).toJson(toJsonT);
  
  const factory Result.success(T data) = ResultSuccess<T>;
  const factory Result.failure(String error) = ResultFailure<T>;
}


