import 'package:dart_json_annotations/dart_json_annotations.dart';

part 'with_example.t.dart';

/// Example: Using @With for union variants
/// Each variant can mix in different mixins

mixin Timestamped {
  DateTime get createdAt => DateTime.now();
}

mixin Identifiable {
  String get id;
}

mixin Cacheable {
  DateTime? get cachedAt;
  void cache() {
    // Implementation
  }
}

/// Example: Sealed class with variants using mixins
///
/// **Note:** This example demonstrates the @With annotation usage.
/// The variant classes (EventUserAction, EventTimestampedEvent, EventFullEvent)
/// are generated by the code generator. The @With annotation tells the generator
/// to mix in the specified mixins.
///
/// **Codegen Status:** Requires code generator support for @With annotation.
/// The generated variant classes should mix in the specified mixins.
@Model(fromJson: true, toJson: true, discriminator: 'type')
sealed class Event {
  const Event._();
  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);

  // Generated variant: EventUserAction (no mixins)
  const factory Event.userAction(String userId) = EventUserAction;

  // Generated variant: EventTimestampedEvent with Timestamped mixin
  @With<Timestamped>()
  const factory Event.timestampedEvent(String userId) = EventTimestampedEvent;

  // Generated variant: EventFullEvent with Timestamped and Identifiable mixins
  @With<Timestamped>()
  @With<Identifiable>()
  const factory Event.fullEvent(String userId, String id) = EventFullEvent;
}
